site_name: RxNExtract Documentation
repo_url: https://github.com/chemplusx/RxNExtract
site_url: https://chemplusx.github.io/RxNExtract/

docs_dir: docs

nav:
  - Home: index.md
  - Installation: INSTALLATION.md
  - Usage: USAGE.md
  - Analysis: ANALYSIS.md
  - Changelog: CHANGELOG.md

theme:
  name: material
  palette:
    primary: blue
    accent: orange
