site_name: RxNExtract Documentation
repo_url: https://github.com/chemplusx/RxNExtract
site_url: https://chemplusx.github.io/RxNExtract/

nav:
  - Home: README.md
  - Installation: docs/INSTALLATION.md
  - Usage: docs/USAGE.md
  - Analysis: docs/ANALYSIS.md
  - Changelog: docs/CHANGELOG.md

theme:
  name: material
  palette:
    primary: blue
    accent: orange